const productos= [
    {   
        id: 1,
        nombre: "Promoción 10 cajas clásicas",
        artista: "12 unidades",
        precio: 45000,
        img: "../assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 2,
        nombre: "Promoción 10 cajas cocktail",
        artista: "18 unidades",
        precio: 45000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 3,
        nombre: "Tequeños clásicos Pizza 8cms",
        artista: "12 unidades",
        precio: 7000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 4,
        nombre: "Tequeños cocktail Pizza 5cms ",
        artista: "18 unidades",
        precio: 7000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 5,
        nombre: "Tequeños clásicos Queso 8cms",
        artista: "24 unidades",
        precio: 12000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 6,
        nombre: "Tequeños cocktail Queso 5cms",
        artista: "35 unidades",
        precio: 12000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 7,
        nombre: "Tequeños clásicos Pizza 8cms",
        artista: "24 unidades",
        precio: 14000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 8,
        nombre: "Tequeños cocktail Pizza 5cms",
        artista: "35 unidades",
        precio: 14000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 9,
        nombre: "Promoción 10 cajas clásicas",
        artista: "24 unidades",
        precio: 90000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 10,
        nombre: "Promoción 10 cajas cocktail",
        artista: "35 unidades",
        precio: 90000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 10,
        nombre: "BOX Tequeños clásicos Queso 8cms",
        artista: "1 Caja de 150 unidades",
        precio: 50000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 10,
        nombre: "Box tequeños cocktail Queso 5cms",
        artista: "210 unidades",
        precio: 50000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 10,
        nombre: "Box tequeburguer 8cms",
        artista: "50 unidades",
        precio: 75000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 10,
        nombre: "Box tequeyoyos 11cms",
        artista: "75 unidades",
        precio: 75000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
    {   
        id: 10,
        nombre: "Tequeños cocktail Pizza 5cms",
        artista: "18 unidades",
        precio: 7000,
        img: "./assets/img/tequenos12unidades.jpg",
    },
];